export const WORKER_THROTTLE_INTERVAL = 100
export const IMAGE_PREVIEW_SIZE = 512
export const IMAGE_GRID_GUTTER_SIZE = 6

export const DEFAULT_CONCURRENT_DOWNLOADS_LIMIT = 10
export const DEFAULT_CONCURRENT_FILE_READS_LIMIT = 3
export const DEFAULT_CONCURRENT_RECORD_OPERATIONS_LIMIT = 3
export const DEFAULT_CONCURRENT_UPLOADS_LIMIT = 3
